robot_description_kinematics:
  manipulator:
    kinematics_solver: pick_ik/PickIkPlugin
    kinematics_solver_timeout: 0.5
    kinematics_solver_attempts: 3
    mode: global
    rotation_scale: 0.5
    position_threshold: 0.001
    orientation_threshold: 0.01
    gd_step_size: 0.0001
    cost_threshold: 0.01
    center_joints_weight: 0.0
    avoid_joint_limits_weight: 0.0
    minimal_displacement_weight: 0.005
